//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 7/7/2010 12:24:24 AM
namespace OrderProcessor.PgpService
{
    
    /// <summary>
    /// There are no comments for PgpEntities in the schema.
    /// </summary>
    public partial class PgpEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new PgpEntities object.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public PgpEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("PgpModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("OrderProcessor.PgpService", typeName.Substring(8)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("OrderProcessor.PgpService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("PgpModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Cards in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Card> Cards
        {
            get
            {
                if ((this._Cards == null))
                {
                    this._Cards = base.CreateQuery<Card>("Cards");
                }
                return this._Cards;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Card> _Cards;
        /// <summary>
        /// There are no comments for CardStyles in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CardStyle> CardStyles
        {
            get
            {
                if ((this._CardStyles == null))
                {
                    this._CardStyles = base.CreateQuery<CardStyle>("CardStyles");
                }
                return this._CardStyles;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CardStyle> _CardStyles;
        /// <summary>
        /// There are no comments for ProcessedCards in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ProcessedCard> ProcessedCards
        {
            get
            {
                if ((this._ProcessedCards == null))
                {
                    this._ProcessedCards = base.CreateQuery<ProcessedCard>("ProcessedCards");
                }
                return this._ProcessedCards;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ProcessedCard> _ProcessedCards;
        /// <summary>
        /// There are no comments for MailSettings in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<MailSetting> MailSettings
        {
            get
            {
                if ((this._MailSettings == null))
                {
                    this._MailSettings = base.CreateQuery<MailSetting>("MailSettings");
                }
                return this._MailSettings;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<MailSetting> _MailSettings;
        /// <summary>
        /// There are no comments for Cards in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCards(Card card)
        {
            base.AddObject("Cards", card);
        }
        /// <summary>
        /// There are no comments for CardStyles in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCardStyles(CardStyle cardStyle)
        {
            base.AddObject("CardStyles", cardStyle);
        }
        /// <summary>
        /// There are no comments for ProcessedCards in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToProcessedCards(ProcessedCard processedCard)
        {
            base.AddObject("ProcessedCards", processedCard);
        }
        /// <summary>
        /// There are no comments for MailSettings in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToMailSettings(MailSetting mailSetting)
        {
            base.AddObject("MailSettings", mailSetting);
        }
    }
    /// <summary>
    /// There are no comments for PgpModel.Card in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CardId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Cards")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CardId")]
    public partial class Card : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Card object.
        /// </summary>
        /// <param name="cardId">Initial value of CardId.</param>
        /// <param name="cardStyleId">Initial value of CardStyleId.</param>
        /// <param name="senderName">Initial value of SenderName.</param>
        /// <param name="senderEmail">Initial value of SenderEmail.</param>
        /// <param name="recipientName">Initial value of RecipientName.</param>
        /// <param name="recipientEmail">Initial value of RecipientEmail.</param>
        /// <param name="greeting">Initial value of Greeting.</param>
        /// <param name="message">Initial value of Message.</param>
        /// <param name="isSent">Initial value of IsSent.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Card CreateCard(int cardId, int cardStyleId, string senderName, string senderEmail, string recipientName, string recipientEmail, string greeting, string message, bool isSent)
        {
            Card card = new Card();
            card.CardId = cardId;
            card.CardStyleId = cardStyleId;
            card.SenderName = senderName;
            card.SenderEmail = senderEmail;
            card.RecipientName = recipientName;
            card.RecipientEmail = recipientEmail;
            card.Greeting = greeting;
            card.Message = message;
            card.IsSent = isSent;
            return card;
        }
        /// <summary>
        /// There are no comments for Property CardId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CardId
        {
            get
            {
                return this._CardId;
            }
            set
            {
                this.OnCardIdChanging(value);
                this._CardId = value;
                this.OnCardIdChanged();
                this.OnPropertyChanged("CardId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CardId;
        partial void OnCardIdChanging(int value);
        partial void OnCardIdChanged();
        /// <summary>
        /// There are no comments for Property CardStyleId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CardStyleId
        {
            get
            {
                return this._CardStyleId;
            }
            set
            {
                this.OnCardStyleIdChanging(value);
                this._CardStyleId = value;
                this.OnCardStyleIdChanged();
                this.OnPropertyChanged("CardStyleId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CardStyleId;
        partial void OnCardStyleIdChanging(int value);
        partial void OnCardStyleIdChanged();
        /// <summary>
        /// There are no comments for Property SenderName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SenderName
        {
            get
            {
                return this._SenderName;
            }
            set
            {
                this.OnSenderNameChanging(value);
                this._SenderName = value;
                this.OnSenderNameChanged();
                this.OnPropertyChanged("SenderName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SenderName;
        partial void OnSenderNameChanging(string value);
        partial void OnSenderNameChanged();
        /// <summary>
        /// There are no comments for Property SenderEmail in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SenderEmail
        {
            get
            {
                return this._SenderEmail;
            }
            set
            {
                this.OnSenderEmailChanging(value);
                this._SenderEmail = value;
                this.OnSenderEmailChanged();
                this.OnPropertyChanged("SenderEmail");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SenderEmail;
        partial void OnSenderEmailChanging(string value);
        partial void OnSenderEmailChanged();
        /// <summary>
        /// There are no comments for Property RecipientName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RecipientName
        {
            get
            {
                return this._RecipientName;
            }
            set
            {
                this.OnRecipientNameChanging(value);
                this._RecipientName = value;
                this.OnRecipientNameChanged();
                this.OnPropertyChanged("RecipientName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RecipientName;
        partial void OnRecipientNameChanging(string value);
        partial void OnRecipientNameChanged();
        /// <summary>
        /// There are no comments for Property RecipientEmail in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RecipientEmail
        {
            get
            {
                return this._RecipientEmail;
            }
            set
            {
                this.OnRecipientEmailChanging(value);
                this._RecipientEmail = value;
                this.OnRecipientEmailChanged();
                this.OnPropertyChanged("RecipientEmail");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RecipientEmail;
        partial void OnRecipientEmailChanging(string value);
        partial void OnRecipientEmailChanged();
        /// <summary>
        /// There are no comments for Property Greeting in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Greeting
        {
            get
            {
                return this._Greeting;
            }
            set
            {
                this.OnGreetingChanging(value);
                this._Greeting = value;
                this.OnGreetingChanged();
                this.OnPropertyChanged("Greeting");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Greeting;
        partial void OnGreetingChanging(string value);
        partial void OnGreetingChanged();
        /// <summary>
        /// There are no comments for Property Message in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Message
        {
            get
            {
                return this._Message;
            }
            set
            {
                this.OnMessageChanging(value);
                this._Message = value;
                this.OnMessageChanged();
                this.OnPropertyChanged("Message");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Message;
        partial void OnMessageChanging(string value);
        partial void OnMessageChanged();
        /// <summary>
        /// There are no comments for Property IsSent in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsSent
        {
            get
            {
                return this._IsSent;
            }
            set
            {
                this.OnIsSentChanging(value);
                this._IsSent = value;
                this.OnIsSentChanged();
                this.OnPropertyChanged("IsSent");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsSent;
        partial void OnIsSentChanging(bool value);
        partial void OnIsSentChanged();
        /// <summary>
        /// There are no comments for CardStyle in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public CardStyle CardStyle
        {
            get
            {
                return this._CardStyle;
            }
            set
            {
                this._CardStyle = value;
                this.OnPropertyChanged("CardStyle");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private CardStyle _CardStyle;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PgpModel.CardStyle in the schema.
    /// </summary>
    /// <KeyProperties>
    /// CardStyleId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CardStyles")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("CardStyleId")]
    public partial class CardStyle : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CardStyle object.
        /// </summary>
        /// <param name="cardStyleId">Initial value of CardStyleId.</param>
        /// <param name="cardName">Initial value of CardName.</param>
        /// <param name="imageUrl">Initial value of ImageUrl.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CardStyle CreateCardStyle(int cardStyleId, string cardName, string imageUrl)
        {
            CardStyle cardStyle = new CardStyle();
            cardStyle.CardStyleId = cardStyleId;
            cardStyle.CardName = cardName;
            cardStyle.ImageUrl = imageUrl;
            return cardStyle;
        }
        /// <summary>
        /// There are no comments for Property CardStyleId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int CardStyleId
        {
            get
            {
                return this._CardStyleId;
            }
            set
            {
                this.OnCardStyleIdChanging(value);
                this._CardStyleId = value;
                this.OnCardStyleIdChanged();
                this.OnPropertyChanged("CardStyleId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _CardStyleId;
        partial void OnCardStyleIdChanging(int value);
        partial void OnCardStyleIdChanged();
        /// <summary>
        /// There are no comments for Property CardName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CardName
        {
            get
            {
                return this._CardName;
            }
            set
            {
                this.OnCardNameChanging(value);
                this._CardName = value;
                this.OnCardNameChanged();
                this.OnPropertyChanged("CardName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CardName;
        partial void OnCardNameChanging(string value);
        partial void OnCardNameChanged();
        /// <summary>
        /// There are no comments for Property ImageUrl in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ImageUrl
        {
            get
            {
                return this._ImageUrl;
            }
            set
            {
                this.OnImageUrlChanging(value);
                this._ImageUrl = value;
                this.OnImageUrlChanged();
                this.OnPropertyChanged("ImageUrl");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ImageUrl;
        partial void OnImageUrlChanging(string value);
        partial void OnImageUrlChanged();
        /// <summary>
        /// There are no comments for Cards in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Card> Cards
        {
            get
            {
                return this._Cards;
            }
            set
            {
                this._Cards = value;
                this.OnPropertyChanged("Cards");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Card> _Cards = new global::System.Data.Services.Client.DataServiceCollection<Card>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PgpModel.ProcessedCard in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ProcessedCardId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ProcessedCards")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ProcessedCardId")]
    public partial class ProcessedCard : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ProcessedCard object.
        /// </summary>
        /// <param name="processedCardId">Initial value of ProcessedCardId.</param>
        /// <param name="rawData">Initial value of RawData.</param>
        /// <param name="serial">Initial value of Serial.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ProcessedCard CreateProcessedCard(int processedCardId, string rawData, string serial)
        {
            ProcessedCard processedCard = new ProcessedCard();
            processedCard.ProcessedCardId = processedCardId;
            processedCard.RawData = rawData;
            processedCard.Serial = serial;
            return processedCard;
        }
        /// <summary>
        /// There are no comments for Property ProcessedCardId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ProcessedCardId
        {
            get
            {
                return this._ProcessedCardId;
            }
            set
            {
                this.OnProcessedCardIdChanging(value);
                this._ProcessedCardId = value;
                this.OnProcessedCardIdChanged();
                this.OnPropertyChanged("ProcessedCardId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ProcessedCardId;
        partial void OnProcessedCardIdChanging(int value);
        partial void OnProcessedCardIdChanged();
        /// <summary>
        /// There are no comments for Property RawData in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string RawData
        {
            get
            {
                return this._RawData;
            }
            set
            {
                this.OnRawDataChanging(value);
                this._RawData = value;
                this.OnRawDataChanged();
                this.OnPropertyChanged("RawData");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _RawData;
        partial void OnRawDataChanging(string value);
        partial void OnRawDataChanged();
        /// <summary>
        /// There are no comments for Property Serial in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Serial
        {
            get
            {
                return this._Serial;
            }
            set
            {
                this.OnSerialChanging(value);
                this._Serial = value;
                this.OnSerialChanged();
                this.OnPropertyChanged("Serial");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Serial;
        partial void OnSerialChanging(string value);
        partial void OnSerialChanged();
        /// <summary>
        /// There are no comments for Property Processed in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<bool> Processed
        {
            get
            {
                return this._Processed;
            }
            set
            {
                this.OnProcessedChanging(value);
                this._Processed = value;
                this.OnProcessedChanged();
                this.OnPropertyChanged("Processed");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<bool> _Processed;
        partial void OnProcessedChanging(global::System.Nullable<bool> value);
        partial void OnProcessedChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for PgpModel.MailSetting in the schema.
    /// </summary>
    /// <KeyProperties>
    /// MailSettingsId
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("MailSettings")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("MailSettingsId")]
    public partial class MailSetting : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new MailSetting object.
        /// </summary>
        /// <param name="mailSettingsId">Initial value of MailSettingsId.</param>
        /// <param name="fromName">Initial value of FromName.</param>
        /// <param name="fromEmail">Initial value of FromEmail.</param>
        /// <param name="smtpServer">Initial value of SmtpServer.</param>
        /// <param name="subject">Initial value of Subject.</param>
        /// <param name="body">Initial value of Body.</param>
        /// <param name="pickupURL">Initial value of PickupURL.</param>
        /// <param name="emailAccountName">Initial value of EmailAccountName.</param>
        /// <param name="emailAccountPassword">Initial value of EmailAccountPassword.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static MailSetting CreateMailSetting(int mailSettingsId, string fromName, string fromEmail, string smtpServer, string subject, string body, string pickupURL, string emailAccountName, string emailAccountPassword)
        {
            MailSetting mailSetting = new MailSetting();
            mailSetting.MailSettingsId = mailSettingsId;
            mailSetting.FromName = fromName;
            mailSetting.FromEmail = fromEmail;
            mailSetting.SmtpServer = smtpServer;
            mailSetting.Subject = subject;
            mailSetting.Body = body;
            mailSetting.PickupURL = pickupURL;
            mailSetting.EmailAccountName = emailAccountName;
            mailSetting.EmailAccountPassword = emailAccountPassword;
            return mailSetting;
        }
        /// <summary>
        /// There are no comments for Property MailSettingsId in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int MailSettingsId
        {
            get
            {
                return this._MailSettingsId;
            }
            set
            {
                this.OnMailSettingsIdChanging(value);
                this._MailSettingsId = value;
                this.OnMailSettingsIdChanged();
                this.OnPropertyChanged("MailSettingsId");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _MailSettingsId;
        partial void OnMailSettingsIdChanging(int value);
        partial void OnMailSettingsIdChanged();
        /// <summary>
        /// There are no comments for Property FromName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FromName
        {
            get
            {
                return this._FromName;
            }
            set
            {
                this.OnFromNameChanging(value);
                this._FromName = value;
                this.OnFromNameChanged();
                this.OnPropertyChanged("FromName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FromName;
        partial void OnFromNameChanging(string value);
        partial void OnFromNameChanged();
        /// <summary>
        /// There are no comments for Property FromEmail in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FromEmail
        {
            get
            {
                return this._FromEmail;
            }
            set
            {
                this.OnFromEmailChanging(value);
                this._FromEmail = value;
                this.OnFromEmailChanged();
                this.OnPropertyChanged("FromEmail");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FromEmail;
        partial void OnFromEmailChanging(string value);
        partial void OnFromEmailChanged();
        /// <summary>
        /// There are no comments for Property CC in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string CC
        {
            get
            {
                return this._CC;
            }
            set
            {
                this.OnCCChanging(value);
                this._CC = value;
                this.OnCCChanged();
                this.OnPropertyChanged("CC");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _CC;
        partial void OnCCChanging(string value);
        partial void OnCCChanged();
        /// <summary>
        /// There are no comments for Property SmtpServer in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string SmtpServer
        {
            get
            {
                return this._SmtpServer;
            }
            set
            {
                this.OnSmtpServerChanging(value);
                this._SmtpServer = value;
                this.OnSmtpServerChanged();
                this.OnPropertyChanged("SmtpServer");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _SmtpServer;
        partial void OnSmtpServerChanging(string value);
        partial void OnSmtpServerChanged();
        /// <summary>
        /// There are no comments for Property Subject in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this._Subject = value;
                this.OnSubjectChanged();
                this.OnPropertyChanged("Subject");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Subject;
        partial void OnSubjectChanging(string value);
        partial void OnSubjectChanged();
        /// <summary>
        /// There are no comments for Property Body in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Body
        {
            get
            {
                return this._Body;
            }
            set
            {
                this.OnBodyChanging(value);
                this._Body = value;
                this.OnBodyChanged();
                this.OnPropertyChanged("Body");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Body;
        partial void OnBodyChanging(string value);
        partial void OnBodyChanged();
        /// <summary>
        /// There are no comments for Property PickupURL in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PickupURL
        {
            get
            {
                return this._PickupURL;
            }
            set
            {
                this.OnPickupURLChanging(value);
                this._PickupURL = value;
                this.OnPickupURLChanged();
                this.OnPropertyChanged("PickupURL");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PickupURL;
        partial void OnPickupURLChanging(string value);
        partial void OnPickupURLChanged();
        /// <summary>
        /// There are no comments for Property EmailAccountName in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EmailAccountName
        {
            get
            {
                return this._EmailAccountName;
            }
            set
            {
                this.OnEmailAccountNameChanging(value);
                this._EmailAccountName = value;
                this.OnEmailAccountNameChanged();
                this.OnPropertyChanged("EmailAccountName");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EmailAccountName;
        partial void OnEmailAccountNameChanging(string value);
        partial void OnEmailAccountNameChanged();
        /// <summary>
        /// There are no comments for Property EmailAccountPassword in the schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string EmailAccountPassword
        {
            get
            {
                return this._EmailAccountPassword;
            }
            set
            {
                this.OnEmailAccountPasswordChanging(value);
                this._EmailAccountPassword = value;
                this.OnEmailAccountPasswordChanged();
                this.OnPropertyChanged("EmailAccountPassword");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _EmailAccountPassword;
        partial void OnEmailAccountPasswordChanging(string value);
        partial void OnEmailAccountPasswordChanged();
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
