//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace PaintGeorgiaPink
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ErrorEdm : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ErrorEdm object using the connection string found in the 'ErrorEdm' section of the application configuration file.
        /// </summary>
        public ErrorEdm() : base("name=ErrorEdm", "ErrorEdm")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ErrorEdm object.
        /// </summary>
        public ErrorEdm(string connectionString) : base(connectionString, "ErrorEdm")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ErrorEdm object.
        /// </summary>
        public ErrorEdm(EntityConnection connection) : base(connection, "ErrorEdm")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ErrorLog> ErrorLogs
        {
            get
            {
                if ((_ErrorLogs == null))
                {
                    _ErrorLogs = base.CreateObjectSet<ErrorLog>("ErrorLogs");
                }
                return _ErrorLogs;
            }
        }
        private ObjectSet<ErrorLog> _ErrorLogs;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ErrorLogs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToErrorLogs(ErrorLog errorLog)
        {
            base.AddObject("ErrorLogs", errorLog);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ErrorLogModel", Name="ErrorLog")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ErrorLog : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ErrorLog object.
        /// </summary>
        /// <param name="errorId">Initial value of the ErrorId property.</param>
        /// <param name="errorLevel">Initial value of the ErrorLevel property.</param>
        /// <param name="errorDate">Initial value of the ErrorDate property.</param>
        public static ErrorLog CreateErrorLog(global::System.Int32 errorId, global::System.String errorLevel, global::System.DateTime errorDate)
        {
            ErrorLog errorLog = new ErrorLog();
            errorLog.ErrorId = errorId;
            errorLog.ErrorLevel = errorLevel;
            errorLog.ErrorDate = errorDate;
            return errorLog;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ErrorId
        {
            get
            {
                return _ErrorId;
            }
            set
            {
                if (_ErrorId != value)
                {
                    OnErrorIdChanging(value);
                    ReportPropertyChanging("ErrorId");
                    _ErrorId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ErrorId");
                    OnErrorIdChanged();
                }
            }
        }
        private global::System.Int32 _ErrorId;
        partial void OnErrorIdChanging(global::System.Int32 value);
        partial void OnErrorIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String StackTrace
        {
            get
            {
                return _StackTrace;
            }
            set
            {
                OnStackTraceChanging(value);
                ReportPropertyChanging("StackTrace");
                _StackTrace = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("StackTrace");
                OnStackTraceChanged();
            }
        }
        private global::System.String _StackTrace;
        partial void OnStackTraceChanging(global::System.String value);
        partial void OnStackTraceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Data
        {
            get
            {
                return _Data;
            }
            set
            {
                OnDataChanging(value);
                ReportPropertyChanging("Data");
                _Data = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Data");
                OnDataChanged();
            }
        }
        private global::System.String _Data;
        partial void OnDataChanging(global::System.String value);
        partial void OnDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TargetSite
        {
            get
            {
                return _TargetSite;
            }
            set
            {
                OnTargetSiteChanging(value);
                ReportPropertyChanging("TargetSite");
                _TargetSite = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TargetSite");
                OnTargetSiteChanged();
            }
        }
        private global::System.String _TargetSite;
        partial void OnTargetSiteChanging(global::System.String value);
        partial void OnTargetSiteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ErrorLevel
        {
            get
            {
                return _ErrorLevel;
            }
            set
            {
                OnErrorLevelChanging(value);
                ReportPropertyChanging("ErrorLevel");
                _ErrorLevel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ErrorLevel");
                OnErrorLevelChanged();
            }
        }
        private global::System.String _ErrorLevel;
        partial void OnErrorLevelChanging(global::System.String value);
        partial void OnErrorLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ErrorDate
        {
            get
            {
                return _ErrorDate;
            }
            set
            {
                OnErrorDateChanging(value);
                ReportPropertyChanging("ErrorDate");
                _ErrorDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ErrorDate");
                OnErrorDateChanged();
            }
        }
        private global::System.DateTime _ErrorDate;
        partial void OnErrorDateChanging(global::System.DateTime value);
        partial void OnErrorDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CustomMessage
        {
            get
            {
                return _CustomMessage;
            }
            set
            {
                OnCustomMessageChanging(value);
                ReportPropertyChanging("CustomMessage");
                _CustomMessage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CustomMessage");
                OnCustomMessageChanged();
            }
        }
        private global::System.String _CustomMessage;
        partial void OnCustomMessageChanging(global::System.String value);
        partial void OnCustomMessageChanged();

        #endregion
    
    }

    #endregion
    
}
