//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PgpModel", "FK_Card_CardStyle", "CardStyle", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PaintGeorgiaPink.CardStyle), "Card", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PaintGeorgiaPink.Card), true)]
[assembly: EdmRelationshipAttribute("PgpModel", "FK_CardShippingInfo_Card", "Card", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PaintGeorgiaPink.Card), "CardShippingInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PaintGeorgiaPink.CardShippingInfo), true)]

#endregion

namespace PaintGeorgiaPink
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PgpEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PgpEntities object using the connection string found in the 'PgpEntities' section of the application configuration file.
        /// </summary>
        public PgpEntities() : base("name=PgpEntities", "PgpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PgpEntities object.
        /// </summary>
        public PgpEntities(string connectionString) : base(connectionString, "PgpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PgpEntities object.
        /// </summary>
        public PgpEntities(EntityConnection connection) : base(connection, "PgpEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Card> Cards
        {
            get
            {
                if ((_Cards == null))
                {
                    _Cards = base.CreateObjectSet<Card>("Cards");
                }
                return _Cards;
            }
        }
        private ObjectSet<Card> _Cards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CardStyle> CardStyles
        {
            get
            {
                if ((_CardStyles == null))
                {
                    _CardStyles = base.CreateObjectSet<CardStyle>("CardStyles");
                }
                return _CardStyles;
            }
        }
        private ObjectSet<CardStyle> _CardStyles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProcessedCard> ProcessedCards
        {
            get
            {
                if ((_ProcessedCards == null))
                {
                    _ProcessedCards = base.CreateObjectSet<ProcessedCard>("ProcessedCards");
                }
                return _ProcessedCards;
            }
        }
        private ObjectSet<ProcessedCard> _ProcessedCards;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MailSetting> MailSettings
        {
            get
            {
                if ((_MailSettings == null))
                {
                    _MailSettings = base.CreateObjectSet<MailSetting>("MailSettings");
                }
                return _MailSettings;
            }
        }
        private ObjectSet<MailSetting> _MailSettings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CardShippingInfo> CardShippingInfoes
        {
            get
            {
                if ((_CardShippingInfoes == null))
                {
                    _CardShippingInfoes = base.CreateObjectSet<CardShippingInfo>("CardShippingInfoes");
                }
                return _CardShippingInfoes;
            }
        }
        private ObjectSet<CardShippingInfo> _CardShippingInfoes;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Cards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCards(Card card)
        {
            base.AddObject("Cards", card);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CardStyles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCardStyles(CardStyle cardStyle)
        {
            base.AddObject("CardStyles", cardStyle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProcessedCards EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProcessedCards(ProcessedCard processedCard)
        {
            base.AddObject("ProcessedCards", processedCard);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MailSettings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMailSettings(MailSetting mailSetting)
        {
            base.AddObject("MailSettings", mailSetting);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CardShippingInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCardShippingInfoes(CardShippingInfo cardShippingInfo)
        {
            base.AddObject("CardShippingInfoes", cardShippingInfo);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PgpModel", Name="Card")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Card : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Card object.
        /// </summary>
        /// <param name="cardId">Initial value of the CardId property.</param>
        /// <param name="cardStyleId">Initial value of the CardStyleId property.</param>
        /// <param name="senderName">Initial value of the SenderName property.</param>
        /// <param name="senderEmail">Initial value of the SenderEmail property.</param>
        /// <param name="recipientName">Initial value of the RecipientName property.</param>
        /// <param name="recipientEmail">Initial value of the RecipientEmail property.</param>
        /// <param name="greeting">Initial value of the Greeting property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        /// <param name="isSent">Initial value of the IsSent property.</param>
        public static Card CreateCard(global::System.Int32 cardId, global::System.Int32 cardStyleId, global::System.String senderName, global::System.String senderEmail, global::System.String recipientName, global::System.String recipientEmail, global::System.String greeting, global::System.String message, global::System.Boolean isSent)
        {
            Card card = new Card();
            card.CardId = cardId;
            card.CardStyleId = cardStyleId;
            card.SenderName = senderName;
            card.SenderEmail = senderEmail;
            card.RecipientName = recipientName;
            card.RecipientEmail = recipientEmail;
            card.Greeting = greeting;
            card.Message = message;
            card.IsSent = isSent;
            return card;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardId
        {
            get
            {
                return _CardId;
            }
            set
            {
                if (_CardId != value)
                {
                    OnCardIdChanging(value);
                    ReportPropertyChanging("CardId");
                    _CardId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CardId");
                    OnCardIdChanged();
                }
            }
        }
        private global::System.Int32 _CardId;
        partial void OnCardIdChanging(global::System.Int32 value);
        partial void OnCardIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardStyleId
        {
            get
            {
                return _CardStyleId;
            }
            set
            {
                OnCardStyleIdChanging(value);
                ReportPropertyChanging("CardStyleId");
                _CardStyleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardStyleId");
                OnCardStyleIdChanged();
            }
        }
        private global::System.Int32 _CardStyleId;
        partial void OnCardStyleIdChanging(global::System.Int32 value);
        partial void OnCardStyleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SenderName
        {
            get
            {
                return _SenderName;
            }
            set
            {
                OnSenderNameChanging(value);
                ReportPropertyChanging("SenderName");
                _SenderName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SenderName");
                OnSenderNameChanged();
            }
        }
        private global::System.String _SenderName;
        partial void OnSenderNameChanging(global::System.String value);
        partial void OnSenderNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SenderEmail
        {
            get
            {
                return _SenderEmail;
            }
            set
            {
                OnSenderEmailChanging(value);
                ReportPropertyChanging("SenderEmail");
                _SenderEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SenderEmail");
                OnSenderEmailChanged();
            }
        }
        private global::System.String _SenderEmail;
        partial void OnSenderEmailChanging(global::System.String value);
        partial void OnSenderEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RecipientName
        {
            get
            {
                return _RecipientName;
            }
            set
            {
                OnRecipientNameChanging(value);
                ReportPropertyChanging("RecipientName");
                _RecipientName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RecipientName");
                OnRecipientNameChanged();
            }
        }
        private global::System.String _RecipientName;
        partial void OnRecipientNameChanging(global::System.String value);
        partial void OnRecipientNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RecipientEmail
        {
            get
            {
                return _RecipientEmail;
            }
            set
            {
                OnRecipientEmailChanging(value);
                ReportPropertyChanging("RecipientEmail");
                _RecipientEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RecipientEmail");
                OnRecipientEmailChanged();
            }
        }
        private global::System.String _RecipientEmail;
        partial void OnRecipientEmailChanging(global::System.String value);
        partial void OnRecipientEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Greeting
        {
            get
            {
                return _Greeting;
            }
            set
            {
                OnGreetingChanging(value);
                ReportPropertyChanging("Greeting");
                _Greeting = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Greeting");
                OnGreetingChanged();
            }
        }
        private global::System.String _Greeting;
        partial void OnGreetingChanging(global::System.String value);
        partial void OnGreetingChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSent
        {
            get
            {
                return _IsSent;
            }
            set
            {
                OnIsSentChanging(value);
                ReportPropertyChanging("IsSent");
                _IsSent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSent");
                OnIsSentChanged();
            }
        }
        private global::System.Boolean _IsSent;
        partial void OnIsSentChanging(global::System.Boolean value);
        partial void OnIsSentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PgpModel", "FK_Card_CardStyle", "CardStyle")]
        public CardStyle CardStyle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardStyle>("PgpModel.FK_Card_CardStyle", "CardStyle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardStyle>("PgpModel.FK_Card_CardStyle", "CardStyle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CardStyle> CardStyleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CardStyle>("PgpModel.FK_Card_CardStyle", "CardStyle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CardStyle>("PgpModel.FK_Card_CardStyle", "CardStyle", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PgpModel", "FK_CardShippingInfo_Card", "CardShippingInfo")]
        public EntityCollection<CardShippingInfo> CardShippingInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CardShippingInfo>("PgpModel.FK_CardShippingInfo_Card", "CardShippingInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CardShippingInfo>("PgpModel.FK_CardShippingInfo_Card", "CardShippingInfo", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PgpModel", Name="CardShippingInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CardShippingInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CardShippingInfo object.
        /// </summary>
        /// <param name="cardShippingInfoId">Initial value of the CardShippingInfoId property.</param>
        /// <param name="cardId">Initial value of the CardId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="address1">Initial value of the Address1 property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="state">Initial value of the State property.</param>
        /// <param name="zip">Initial value of the Zip property.</param>
        public static CardShippingInfo CreateCardShippingInfo(global::System.Int32 cardShippingInfoId, global::System.Int32 cardId, global::System.String name, global::System.String address1, global::System.String city, global::System.String state, global::System.Int32 zip)
        {
            CardShippingInfo cardShippingInfo = new CardShippingInfo();
            cardShippingInfo.CardShippingInfoId = cardShippingInfoId;
            cardShippingInfo.CardId = cardId;
            cardShippingInfo.Name = name;
            cardShippingInfo.Address1 = address1;
            cardShippingInfo.City = city;
            cardShippingInfo.State = state;
            cardShippingInfo.Zip = zip;
            return cardShippingInfo;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardShippingInfoId
        {
            get
            {
                return _CardShippingInfoId;
            }
            set
            {
                if (_CardShippingInfoId != value)
                {
                    OnCardShippingInfoIdChanging(value);
                    ReportPropertyChanging("CardShippingInfoId");
                    _CardShippingInfoId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CardShippingInfoId");
                    OnCardShippingInfoIdChanged();
                }
            }
        }
        private global::System.Int32 _CardShippingInfoId;
        partial void OnCardShippingInfoIdChanging(global::System.Int32 value);
        partial void OnCardShippingInfoIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardId
        {
            get
            {
                return _CardId;
            }
            set
            {
                OnCardIdChanging(value);
                ReportPropertyChanging("CardId");
                _CardId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CardId");
                OnCardIdChanged();
            }
        }
        private global::System.Int32 _CardId;
        partial void OnCardIdChanging(global::System.Int32 value);
        partial void OnCardIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.Int32 _Zip;
        partial void OnZipChanging(global::System.Int32 value);
        partial void OnZipChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PgpModel", "FK_CardShippingInfo_Card", "Card")]
        public Card Card
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Card>("PgpModel.FK_CardShippingInfo_Card", "Card").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Card>("PgpModel.FK_CardShippingInfo_Card", "Card").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Card> CardReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Card>("PgpModel.FK_CardShippingInfo_Card", "Card");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Card>("PgpModel.FK_CardShippingInfo_Card", "Card", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PgpModel", Name="CardStyle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CardStyle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CardStyle object.
        /// </summary>
        /// <param name="cardStyleId">Initial value of the CardStyleId property.</param>
        /// <param name="cardName">Initial value of the CardName property.</param>
        /// <param name="imageUrl">Initial value of the ImageUrl property.</param>
        public static CardStyle CreateCardStyle(global::System.Int32 cardStyleId, global::System.String cardName, global::System.String imageUrl)
        {
            CardStyle cardStyle = new CardStyle();
            cardStyle.CardStyleId = cardStyleId;
            cardStyle.CardName = cardName;
            cardStyle.ImageUrl = imageUrl;
            return cardStyle;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CardStyleId
        {
            get
            {
                return _CardStyleId;
            }
            set
            {
                if (_CardStyleId != value)
                {
                    OnCardStyleIdChanging(value);
                    ReportPropertyChanging("CardStyleId");
                    _CardStyleId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CardStyleId");
                    OnCardStyleIdChanged();
                }
            }
        }
        private global::System.Int32 _CardStyleId;
        partial void OnCardStyleIdChanging(global::System.Int32 value);
        partial void OnCardStyleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CardName
        {
            get
            {
                return _CardName;
            }
            set
            {
                OnCardNameChanging(value);
                ReportPropertyChanging("CardName");
                _CardName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CardName");
                OnCardNameChanged();
            }
        }
        private global::System.String _CardName;
        partial void OnCardNameChanging(global::System.String value);
        partial void OnCardNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ImageUrl
        {
            get
            {
                return _ImageUrl;
            }
            set
            {
                OnImageUrlChanging(value);
                ReportPropertyChanging("ImageUrl");
                _ImageUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ImageUrl");
                OnImageUrlChanged();
            }
        }
        private global::System.String _ImageUrl;
        partial void OnImageUrlChanging(global::System.String value);
        partial void OnImageUrlChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PgpModel", "FK_Card_CardStyle", "Card")]
        public EntityCollection<Card> Cards
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Card>("PgpModel.FK_Card_CardStyle", "Card");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Card>("PgpModel.FK_Card_CardStyle", "Card", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PgpModel", Name="MailSetting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MailSetting : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MailSetting object.
        /// </summary>
        /// <param name="mailSettingsId">Initial value of the MailSettingsId property.</param>
        /// <param name="fromName">Initial value of the FromName property.</param>
        /// <param name="fromEmail">Initial value of the FromEmail property.</param>
        /// <param name="smtpServer">Initial value of the SmtpServer property.</param>
        /// <param name="subject">Initial value of the Subject property.</param>
        /// <param name="body">Initial value of the Body property.</param>
        /// <param name="pickupURL">Initial value of the PickupURL property.</param>
        /// <param name="emailAccountName">Initial value of the EmailAccountName property.</param>
        /// <param name="emailAccountPassword">Initial value of the EmailAccountPassword property.</param>
        /// <param name="port">Initial value of the Port property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        public static MailSetting CreateMailSetting(global::System.Int32 mailSettingsId, global::System.String fromName, global::System.String fromEmail, global::System.String smtpServer, global::System.String subject, global::System.String body, global::System.String pickupURL, global::System.String emailAccountName, global::System.String emailAccountPassword, global::System.Int32 port, global::System.Boolean active)
        {
            MailSetting mailSetting = new MailSetting();
            mailSetting.MailSettingsId = mailSettingsId;
            mailSetting.FromName = fromName;
            mailSetting.FromEmail = fromEmail;
            mailSetting.SmtpServer = smtpServer;
            mailSetting.Subject = subject;
            mailSetting.Body = body;
            mailSetting.PickupURL = pickupURL;
            mailSetting.EmailAccountName = emailAccountName;
            mailSetting.EmailAccountPassword = emailAccountPassword;
            mailSetting.Port = port;
            mailSetting.Active = active;
            return mailSetting;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MailSettingsId
        {
            get
            {
                return _MailSettingsId;
            }
            set
            {
                if (_MailSettingsId != value)
                {
                    OnMailSettingsIdChanging(value);
                    ReportPropertyChanging("MailSettingsId");
                    _MailSettingsId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MailSettingsId");
                    OnMailSettingsIdChanged();
                }
            }
        }
        private global::System.Int32 _MailSettingsId;
        partial void OnMailSettingsIdChanging(global::System.Int32 value);
        partial void OnMailSettingsIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromName
        {
            get
            {
                return _FromName;
            }
            set
            {
                OnFromNameChanging(value);
                ReportPropertyChanging("FromName");
                _FromName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FromName");
                OnFromNameChanged();
            }
        }
        private global::System.String _FromName;
        partial void OnFromNameChanging(global::System.String value);
        partial void OnFromNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FromEmail
        {
            get
            {
                return _FromEmail;
            }
            set
            {
                OnFromEmailChanging(value);
                ReportPropertyChanging("FromEmail");
                _FromEmail = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FromEmail");
                OnFromEmailChanged();
            }
        }
        private global::System.String _FromEmail;
        partial void OnFromEmailChanging(global::System.String value);
        partial void OnFromEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CC
        {
            get
            {
                return _CC;
            }
            set
            {
                OnCCChanging(value);
                ReportPropertyChanging("CC");
                _CC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CC");
                OnCCChanged();
            }
        }
        private global::System.String _CC;
        partial void OnCCChanging(global::System.String value);
        partial void OnCCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SmtpServer
        {
            get
            {
                return _SmtpServer;
            }
            set
            {
                OnSmtpServerChanging(value);
                ReportPropertyChanging("SmtpServer");
                _SmtpServer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SmtpServer");
                OnSmtpServerChanged();
            }
        }
        private global::System.String _SmtpServer;
        partial void OnSmtpServerChanging(global::System.String value);
        partial void OnSmtpServerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Subject
        {
            get
            {
                return _Subject;
            }
            set
            {
                OnSubjectChanging(value);
                ReportPropertyChanging("Subject");
                _Subject = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Subject");
                OnSubjectChanged();
            }
        }
        private global::System.String _Subject;
        partial void OnSubjectChanging(global::System.String value);
        partial void OnSubjectChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Body
        {
            get
            {
                return _Body;
            }
            set
            {
                OnBodyChanging(value);
                ReportPropertyChanging("Body");
                _Body = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Body");
                OnBodyChanged();
            }
        }
        private global::System.String _Body;
        partial void OnBodyChanging(global::System.String value);
        partial void OnBodyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PickupURL
        {
            get
            {
                return _PickupURL;
            }
            set
            {
                OnPickupURLChanging(value);
                ReportPropertyChanging("PickupURL");
                _PickupURL = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PickupURL");
                OnPickupURLChanged();
            }
        }
        private global::System.String _PickupURL;
        partial void OnPickupURLChanging(global::System.String value);
        partial void OnPickupURLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAccountName
        {
            get
            {
                return _EmailAccountName;
            }
            set
            {
                OnEmailAccountNameChanging(value);
                ReportPropertyChanging("EmailAccountName");
                _EmailAccountName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAccountName");
                OnEmailAccountNameChanged();
            }
        }
        private global::System.String _EmailAccountName;
        partial void OnEmailAccountNameChanging(global::System.String value);
        partial void OnEmailAccountNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAccountPassword
        {
            get
            {
                return _EmailAccountPassword;
            }
            set
            {
                OnEmailAccountPasswordChanging(value);
                ReportPropertyChanging("EmailAccountPassword");
                _EmailAccountPassword = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAccountPassword");
                OnEmailAccountPasswordChanged();
            }
        }
        private global::System.String _EmailAccountPassword;
        partial void OnEmailAccountPasswordChanging(global::System.String value);
        partial void OnEmailAccountPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Port
        {
            get
            {
                return _Port;
            }
            set
            {
                OnPortChanging(value);
                ReportPropertyChanging("Port");
                _Port = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Port");
                OnPortChanged();
            }
        }
        private global::System.Int32 _Port;
        partial void OnPortChanging(global::System.Int32 value);
        partial void OnPortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PgpModel", Name="ProcessedCard")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProcessedCard : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProcessedCard object.
        /// </summary>
        /// <param name="processedCardId">Initial value of the ProcessedCardId property.</param>
        /// <param name="rawData">Initial value of the RawData property.</param>
        /// <param name="serial">Initial value of the Serial property.</param>
        public static ProcessedCard CreateProcessedCard(global::System.Int32 processedCardId, global::System.String rawData, global::System.String serial)
        {
            ProcessedCard processedCard = new ProcessedCard();
            processedCard.ProcessedCardId = processedCardId;
            processedCard.RawData = rawData;
            processedCard.Serial = serial;
            return processedCard;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProcessedCardId
        {
            get
            {
                return _ProcessedCardId;
            }
            set
            {
                if (_ProcessedCardId != value)
                {
                    OnProcessedCardIdChanging(value);
                    ReportPropertyChanging("ProcessedCardId");
                    _ProcessedCardId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ProcessedCardId");
                    OnProcessedCardIdChanged();
                }
            }
        }
        private global::System.Int32 _ProcessedCardId;
        partial void OnProcessedCardIdChanging(global::System.Int32 value);
        partial void OnProcessedCardIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RawData
        {
            get
            {
                return _RawData;
            }
            set
            {
                OnRawDataChanging(value);
                ReportPropertyChanging("RawData");
                _RawData = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("RawData");
                OnRawDataChanged();
            }
        }
        private global::System.String _RawData;
        partial void OnRawDataChanging(global::System.String value);
        partial void OnRawDataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Serial
        {
            get
            {
                return _Serial;
            }
            set
            {
                OnSerialChanging(value);
                ReportPropertyChanging("Serial");
                _Serial = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Serial");
                OnSerialChanged();
            }
        }
        private global::System.String _Serial;
        partial void OnSerialChanging(global::System.String value);
        partial void OnSerialChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Processed
        {
            get
            {
                return _Processed;
            }
            set
            {
                OnProcessedChanging(value);
                ReportPropertyChanging("Processed");
                _Processed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Processed");
                OnProcessedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Processed;
        partial void OnProcessedChanging(Nullable<global::System.Boolean> value);
        partial void OnProcessedChanged();

        #endregion
    
    }

    #endregion
    
}
